# Generated by Django 4.1 on 2022-10-24 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_apikeywordsmodel_api_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikeywordsmodel',
            name='api_choices',
        ),
        migrations.RemoveField(
            model_name='apikeywordsmodel',
            name='num_keywords',
        ),
    ]
