# Generated by Django 4.1 on 2022-10-24 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_remove_apikeywordsmodel_api_choices_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApiKeywordsModel',
            new_name='ApiModel',
        ),
    ]
